name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lowercase REPO
        id: lower-repo
        run: |
          echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and tag Docker image
        run: |
          docker build . -t ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.lower-repo.outputs.repository }}:latest

